"""initial migration

Revision ID: 6f09e1ca4d62
Revises: 
Create Date: 2026-09-07 11:59:35.309014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f09e1ca4d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('weekend_day', sa.Integer(), nullable=False, comment='Day-of-week considered weekend (5=Friday for Algeria)'),
    sa.Column('current_term', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academy_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('default_plan_duration', sa.Integer(), nullable=False),
    sa.Column('billing_reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('due_date_reminder_timing', sa.Enum('same_day', 'custom', name='reminder_timing_enum'), nullable=False),
    sa.Column('whatsapp_template', sa.Text(), nullable=True),
    sa.Column('auto_checkout_enabled', sa.Boolean(), nullable=False),
    sa.Column('end_class_popup_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_theme', sa.Enum('light', 'dark', name='theme_enum'), nullable=False),
    sa.Column('default_font_size', sa.Enum('normal', 'large', name='font_size_enum'), nullable=False),
    sa.Column('default_language', sa.Enum('fr', 'ar', name='language_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academy_id')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='30 for monthly, 90 for term'),
    sa.Column('amount_da', sa.Integer(), nullable=False, comment='Price in Algerian Dinars'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('parent_phone', sa.String(length=30), nullable=True, comment='Primary parent/guardian emergency number'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False, comment='Hex color for calendar display'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.Enum('starter', 'pro', 'scaler', name='subscription_tier_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'trialing', name='subscription_status_enum'), nullable=False),
    sa.Column('invoicing_method', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academy_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='Primary subject (Math, French, English, Science)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.Enum('hourly', 'per_student', name='contract_type_enum'), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=True, comment='DA per hour — for hourly contracts'),
    sa.Column('per_student_rate', sa.Integer(), nullable=True, comment='DA per student — for per-student contracts'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('owner', 'staff', name='user_role_enum'), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Owner password for login'),
    sa.Column('picture', sa.JSON(), nullable=True, comment="{ type: 'preset', colors: [hex1, hex2] } or { type: 'upload', dataUrl: '...' }"),
    sa.Column('avatar_color_1', sa.String(length=7), nullable=True, comment='Legacy gradient start color'),
    sa.Column('avatar_color_2', sa.String(length=7), nullable=True, comment='Legacy gradient end color'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Who performed the action'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='student | teacher | class | session | billing | payment'),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False, comment='created | updated | deleted | checked_in | checked_out | payment_received | payment_overdue | enrolled | withdrawn'),
    sa.Column('description', sa.Text(), nullable=True, comment="Human-readable: 'Payment received — Karim M.'"),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Contextual data: amount, session info, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='Math, French, English, Science (extensible)'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='Hex color for calendar palette styling, e.g. #b3872a'),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardians',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True, comment='Free-form relationship label (Mother, Father, Uncle...)'),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='null = broadcast to all academy users'),
    sa.Column('type', sa.Enum('payment_reminder', 'class_ending', 'enrollment_request', 'overdue_alert', 'general', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True, comment='Array of {label, variant} for action buttons'),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_billings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('payment_plan_id', sa.String(length=36), nullable=False),
    sa.Column('amount_da', sa.Integer(), nullable=False, comment='Amount due for this cycle'),
    sa.Column('status', sa.Enum('paid', 'due', 'overdue', name='billing_status_enum'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True, comment='Actual amount paid (may differ if partial)'),
    sa.Column('cycle_start', sa.Date(), nullable=False),
    sa.Column('cycle_end', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_payrolls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=8, scale=2), nullable=False, comment='Sum of logged hours (hourly contracts)'),
    sa.Column('total_students', sa.Integer(), nullable=False, comment='Active student count (per-student contracts)'),
    sa.Column('rate_applied', sa.Integer(), nullable=False, comment='Rate used for calculation'),
    sa.Column('calculated_amount', sa.Integer(), nullable=False, comment='total_hours × rate OR total_students × rate'),
    sa.Column('status', sa.Enum('pending', 'settled', 'overdue', name='payroll_status_enum'), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'withdrawn', name='enrollment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_billing_id', sa.String(length=36), nullable=False),
    sa.Column('amount_da', sa.Integer(), nullable=False, comment='Amount paid in this transaction'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='Cash, bank transfer, etc.'),
    sa.Column('recorded_by', sa.String(length=36), nullable=False, comment='Which staff member logged the payment'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_billing_id'], ['student_billings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Sun, 1=Mon, ..., 6=Sat'),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('academy_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True, comment='Link back to recurring slot — null for custom sessions'),
    sa.Column('teacher_id', sa.String(length=36), nullable=False, comment='Denormalized from Class at creation time'),
    sa.Column('classroom_id', sa.String(length=36), nullable=True, comment='Denormalized from Schedule at creation time'),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='Denormalized from Class'),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='session_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academies.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.String(length=36), nullable=True, comment='Which staff member logged the check-in'),
    sa.Column('payment_status', sa.Enum('paid', 'due', 'overdue', name='session_payment_status_enum'), nullable=False, comment='Denormalized snapshot for this session'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_hours_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False, comment='Duration of the session in hours'),
    sa.Column('logged_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_hours_logs')
    op.drop_table('session_students')
    op.drop_table('sessions')
    op.drop_table('schedules')
    op.drop_table('payment_logs')
    op.drop_table('enrollments')
    op.drop_table('teacher_payrolls')
    op.drop_table('student_billings')
    op.drop_table('notifications')
    op.drop_table('guardians')
    op.drop_table('classes')
    op.drop_table('activity_logs')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('subscriptions')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('payment_plans')
    op.drop_table('classrooms')
    op.drop_table('academy_settings')
    op.drop_table('academies')
    # ### end Alembic commands ###
